# Generated by Django 5.0.6 on 2024-07-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daraja', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='b2btransaction',
            name='debit_party_affected_account_balance',
        ),
        migrations.AddField(
            model_name='b2btransaction',
            name='recipient_type',
            field=models.CharField(choices=[(0, 'Complete'), (1, 'Pending'), (2, 'Failed')], default='paybill', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='b2btransaction',
            name='debit_account_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='b2btransaction',
            name='initiator_account_current_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
