# Generated by Django 5.0.6 on 2024-08-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daraja', '0002_b2bexpresstransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2bexpresstransaction',
            name='ailure_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
