# Generated by Django 5.0.6 on 2024-07-22 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daraja', '0002_remove_b2btransaction_debit_party_affected_account_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='b2btransaction',
            old_name='paybill_number',
            new_name='recipient_number',
        ),
    ]
