# Generated by Django 5.0.6 on 2024-07-22 13:18

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daraja', '0003_rename_paybill_number_b2btransaction_recipient_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2btransaction',
            name='requester',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
