# Generated by Django 5.0.6 on 2024-07-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daraja', '0004_b2btransaction_requester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b2btransaction',
            name='debit_party_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
