# Generated by Django 5.0.6 on 2024-07-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daraja', '0005_alter_b2btransaction_debit_party_charges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b2btransaction',
            name='recipient_type',
            field=models.CharField(choices=[('paybill', 'PayBill'), ('buy_goods', 'BuyGoods')], max_length=20),
        ),
    ]
