# Generated by Django 5.0.6 on 2024-07-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daraja', '0006_alter_b2btransaction_recipient_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b2btransaction',
            name='recipient_type',
            field=models.CharField(choices=[('paybill', 'PayBill'), ('buygoods', 'BuyGoods')], max_length=20),
        ),
    ]
