# Generated by Django 5.0.6 on 2024-07-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daraja', '0007_alter_b2btransaction_recipient_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2btransaction',
            name='failure_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
