# Generated by Django 5.0.6 on 2024-06-06 13:50

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='B2CTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('conversation_id', models.CharField(max_length=255, unique=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('transaction_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('working_account_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('utility_account_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('transaction_time', models.DateTimeField(blank=True, null=True)),
                ('recipient_phonenumber', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('recipient_public_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[(0, 'Complete'), (1, 'Pending')], default=1, max_length=10)),
                ('ip', models.CharField(blank=True, max_length=200, null=True)),
                ('occassion', models.CharField(blank=True, max_length=200, null=True)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'B2CTransaction',
                'verbose_name_plural': 'B2CTransactions',
            },
        ),
        migrations.CreateModel(
            name='STKTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('checkout_request_id', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[(0, 'Complete'), (1, 'Pending')], default=1, max_length=10)),
                ('receipt_no', models.CharField(blank=True, max_length=200, null=True)),
                ('ip', models.CharField(blank=True, max_length=200, null=True)),
                ('transaction_date', models.CharField(blank=True, max_length=200, null=True)),
                ('reference', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'STKTransaction',
                'verbose_name_plural': 'STKTransactions',
            },
        ),
    ]
