# Generated by Django 5.0.6 on 2024-06-11 13:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2ctransaction',
            name='originator_conversation_id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
