# Generated by Django 5.0.6 on 2024-07-01 13:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0002_b2ctransaction_originator_conversation_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='B2BTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('conversation_id', models.CharField(max_length=255, unique=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[(0, 'Complete'), (1, 'Pending')], default=1, max_length=10)),
                ('ip', models.CharField(blank=True, max_length=200, null=True)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('originator_conversation_id', models.CharField(blank=True, default=uuid.uuid4, max_length=255, unique=True)),
                ('amount', models.IntegerField()),
                ('debit_account_balance', models.CharField(blank=True, max_length=255, null=True)),
                ('debit_party_affected_account_balance', models.CharField(blank=True, max_length=255, null=True)),
                ('debit_party_charges', models.IntegerField(blank=True, null=True)),
                ('transaction_time', models.DateTimeField(blank=True, null=True)),
                ('recipient_public_name', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(blank=True, max_length=255, null=True)),
                ('paybill_number', models.IntegerField(blank=True, null=True)),
                ('account_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('initiatoe_account_current_balance', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'B2BTransaction',
                'verbose_name_plural': 'B2BTransactions',
            },
        ),
    ]
